### PR TITLE
php 7.2 compatibility

### PR DESCRIPTION
**Pull request by eavilesmejia**
on PHP7.2 sizeof() throw an error when the param is not an array nor object:

sizeof(): Parameter must be an array or an object that implements Countable

### CODE REVIEW

**Comment by tonydspaniard** [comment]
@eavilesmejia AFAIK there is a major issue too and is that mcrypt was deprecated, how did you managed to make it work with PHP 7.2? Any advice? Thanks

**Comment by itinance** [comment]
Any news on this?

**Comment by quentinlesceller** [comment]
Going to take a look.

**Comment by quentinlesceller** [comment]
With #111. PHP Client will only works with PHP >=7.1.0.

**Pull request closed without merging**
